name: Linux

on: [push, pull_request]

defaults:
  run:
    working-directory: Examples

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        compiler: [g++-9, g++-10, clang++-10, clang++-11, clang++-12]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      env:
        CXX: ${{ matrix.compiler }}
      run: mkdir ${{ matrix.configuration }} && cd ${{ matrix.configuration }} && cmake -D CMAKE_BUILD_TYPE=${{ matrix.configuration }} ..
    - name: build
      run: cd ${{ matrix.configuration }} && make -j $(nproc --all)
