name: Linux

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        compiler: [g++-7, g++-8, g++-9, g++-10, clang++-6.0, clang++-7, clang++-8, clang++-9, clang++-10, clang++-11, clang++-12]
        configuration: [Debug, Release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install compiler
      run: sudo apt-get install -y ${{ matrix.compiler }}
    - name: configure
      run: CXX=${{ matrix.compiler }} cmake -D CMAKE_BUILD_TYPE=${{ matrix.configuration }} -D BUILD_EXAMPLES=1 -S . -B ${{ matrix.configuration }}
    - name: build
      run: cmake --build ${{ matrix.configuration }} -j $(nproc --all)

  tests:
    strategy:
      matrix:
        compiler: [g++-7, g++-8, g++-9, g++-10, clang++-6.0, clang++-7, clang++-8, clang++-9, clang++-10, clang++-11, clang++-12]
        configuration: [Debug, Release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install compiler
      run: sudo apt-get install -y ${{ matrix.compiler }} libgtest-dev
    - name: configure
      run: CXX=${{ matrix.compiler }} cmake -D CMAKE_BUILD_TYPE=${{ matrix.configuration }} -D BUILD_TESTS=1 -S . -B ${{ matrix.configuration }}
    - name: build
      run: cmake --build ${{ matrix.configuration }} -j $(nproc --all)
    - name: Run unit tests
      run: cd ${{ matrix.configuration }} && ctest
