name: Linux

on: [push, pull_request]

defaults:
  run:
    working-directory: Examples

jobs:
  build:
    strategy:
      matrix:
        compiler: [g++-7, g++-8, g++-9, g++-10, clang++-8, clang++-9, clang++-10, clang++-11, clang++-12]
        configuration: [Debug, Release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install compiler
      run: sudo apt-get install -y ${{ matrix.compiler }}
    - name: configure
      env:
        CXX: ${{ matrix.compiler }}
      run: mkdir ${{ matrix.configuration }} && cd ${{ matrix.configuration }} && cmake -D CMAKE_BUILD_TYPE=${{ matrix.configuration }} ..
    - name: build
      run: cd ${{ matrix.configuration }} && make -j $(nproc --all)
