name: macOS

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        xcode: [12.4, 12.3]
        configuration: [Debug, Release]
    runs-on: macos-10.15
    name: build (Xcode ${{ matrix.xcode }}, ${{ matrix.configuration }})
    steps:
    - uses: actions/checkout@v2
    - name: Install GTest
      run: brew install googletest
    - name: configure
      run: DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer cmake -D CMAKE_BUILD_TYPE=${{ matrix.configuration }} -D BUILD_EXAMPLES=1 -S . -B ${{ matrix.configuration }}
    - name: build
      run: cmake --build ${{ matrix.configuration }} -j $(sysctl -n hw.ncpu)
  tests:
    strategy:
      matrix:
        xcode: [12.4, 12.3]
        configuration: [Debug, Release]
    runs-on: macos-10.15
    name: build (Xcode ${{ matrix.xcode }}, ${{ matrix.configuration }})
    steps:
    - uses: actions/checkout@v2
    - name: Install GTest
      run: brew install googletest
    - name: configure
      run: DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer cmake -D CMAKE_BUILD_TYPE=${{ matrix.configuration }} -D BUILD_TESTS=1 -S . -B ${{ matrix.configuration }}
    - name: build
      run: cmake --build ${{ matrix.configuration }} -j $(sysctl -n hw.ncpu)
    - name: Run unit tests
      run: cd ${{ matrix.configuration }} && ctest
