name: macOS

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        xcode: [12.4, 12.3, 12.2, 12.1.1, 12.1, 12.0.1, 11.7, 11.6, 11.5, 11.4.1, 11.3.1, 11.2.1, 10.3]
        configuration: [Debug, Release]
    runs-on: macos-10.15
    name: build and test (Xcode ${{ matrix.xcode }}, ${{ matrix.configuration }})
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer cmake -D CMAKE_BUILD_TYPE=${{ matrix.configuration }} -D BUILD_EXAMPLES=1 -D BUILD_TESTS=1 -S . -B ${{ matrix.configuration }}
    - name: build
      run: cmake --build ${{ matrix.configuration }} -j $(sysctl -n hw.ncpu)
    - name: Run unit tests
      run: cd ${{ matrix.configuration }} && ctest --output-on-failure -j $(sysctl -n hw.ncpu)
